apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: my-app-container
          image: proxium/nodejs-sample:master-ba9cb36241888749c664778112f7be5231525d63
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
