name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t proxium/nodejs-sample:$GITHUB_SHA --load .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username proxium --password-stdin
          docker push proxium/nodejs-sample:$GITHUB_SHA

      - name: Update k8s image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(select(documentIndex == 0) | .spec.template.spec.containers[0].image) = "proxium/nodejs-sample:${GITHUB_SHA}"' deployments/k8s.yml

      - name: Commit manifest file (optional, consider GitOps if applicable)
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add deployments/k8s.yml
          git commit -m "Deployed image version $GITHUB_SHA"
          git push --set-upstream origin master