name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t proxium/nodejs-sample:$GITHUB_REF_NAME-$GITHUB_SHA --load .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username proxium --password-stdin
          docker push proxium/nodejs-sample:$GITHUB_REF_NAME-$GITHUB_SHA

      - name: Update k8s image
        uses: Charlyzzz/update-k8s-image@v1.7.1
        with:
          manifest-path: deployments/k8s.yml
          name: my-app-container
          
      - name: Commit manifest file
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@gmail.com"
          git pull
          git add .  
          git commit -m "updating newer image"
          git push --set-upstream origin master