name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: nodejs-sample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update k8s image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(select(documentIndex == 0) | .spec.template.spec.containers[0].image) = "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"' deployments/k8s.yml

      - name: Commit manifest file (optional, consider GitOps if applicable)
        run: |
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git pull
          git add deployments/k8s.yml
          git commit -m "Deployed image version ${{ github.sha }}"
          git push --set-upstream origin master