name: Build, Push, and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t proxium/nodejs-sample:$GITHUB_REF_NAME-$GITHUB_SHA --load .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username proxium --password-stdin
          docker push proxium/nodejs-sample:$GITHUB_REF_NAME-$GITHUB_SHA

      - name: Update k8s image
        uses: Charlyzzz/update-k8s-image@v1.7.1
        with:
          manifest-path: deployments/k8s.yml
          container-name: my-app-container

      - name: Update k8s image
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '(select(documentIndex == 0) | .spec.template.spec.containers[0].image) = "proxium/nodejs-sample:${{ env.GITHUB_BRANCH }}"' deployments/k8s.yml

      - name: Commit manifest file
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add .  
          git commit -m "Updating newer image"
          git push --set-upstream origin master