name: Build, Push, and Deploy

on:
  push:
    branches:
      - master
# see https://stackoverflow.com/a/76181305
env:
  REGISTRY: docker.io
  IMAGE_NAME: nodejs-sample
#images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: debug
        run: |
          echo "My variable value is: ${GITHUB_ACTOR}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"


      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: "${GITHUB_ACTOR}/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"

      # - name: Update k8s image
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq -i '(select(documentIndex == 0) | .spec.template.spec.containers[0].image) = "proxium/${{ env.IMAGE_NAME }}:${GITHUB_SHA}"' deployments/k8s.yml

      # - name: Commit manifest file (optional, consider GitOps if applicable)
      #   run: |
      #     git config --global user.name "${GITHUB_ACTOR}"
      #     git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      #     git pull
      #     git add deployments/k8s.yml
      #     git commit -m "Deployed image version $GITHUB_SHA"
      #     git push --set-upstream origin master